Vagrant::Config.run do |config|
  config.vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

  # see my comment regarding mounting home dirs and using custom user at
  # https://groups.google.com/d/topic/vagrant-up/5vWiQgweYdI/discussion
  config.vm.share_folder "jaybuff-home", "/home/jaybuff", "/Users/jaybuff", :owner=> 'jaybuff', :group=>'jaybuff'
  config.ssh.username = "jaybuff"

  # ludicrous - this is needed or you won't be able to create symlinks
  # in mounted home directory
  # https://www.virtualbox.org/ticket/10085
  config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/jaybuff-home", "1"]

  config.ssh.forward_agent = true
  config.vm.box = "ol6u3"

  %w(horizon ovs-build quantum-test quantum keystone glance build new keystone-test glance-test nova nova-test).each do |name|
      config.vm.define name do |named_vm|
        named_vm.vm.host_name = name
        if name == "horizon"
            named_vm.vm.forward_port 8080, 8080
        end
      end
  end

end
