Vagrant::Config.run do |config|
  config.ssh.username = "jaybuff"

  config.vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  config.vm.share_folder "jaybuff-home", "/home/jaybuff", "/Users/jaybuff", :owner=> 'jaybuff', :group=>'jaybuff'
  config.ssh.forward_agent = true
  config.vm.box = "ol6u3"

  config.vm.define :keystone
  config.vm.define :build
end
